AWSTemplateFormatVersion : '2010-09-09'
Globals:
  Api:
    OpenApiVersion: 3.0.1
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Domain:
        CertificateArn: pCertificateArn
        BasePath:
          - pVersion
        DomainName: pCustomDomainName        
      EndpointConfiguration: REGIONAL
      StageName: pStageName
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
      Handler: hello.lambdaHandler
      Runtime: nodejs12.x
      Events:
        AuthApi:
          Type: Api
          Properties:
            Path: /hello-main
            Method: GET
            RestApiId: !Ref ApiGatewayApi
  
  Route53CNAMERecord:
    Type: Custom::A
    Properties: 
      ServiceToken: arn:aws:sns:us-east-1:739653925675:RequestRoute53CNAME
      Source: pCustomDomainName
      Target: !Join ['',['d-',!Ref ApiGatewayApi, !Sub '.execute-api.${AWS::Region}.amazonaws.com'] ]
      HostedZone: pHostedZoneId

Outputs:
  ApiGatewayApiID:
    Description: The ID of the API
    Value: !Ref ApiGatewayApi

