AWSTemplateFormatVersion : '2010-09-09'
Globals:
  Api:
    OpenApiVersion: 3.0.1
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: REGIONAL
      StageName: pStageName
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
      Handler: hello.lambdaHandler
      Runtime: nodejs12.x
      Events:
        AuthApi:
          Type: Api
          Properties:
            Path: /hello-main
            Method: GET
            RestApiId: !Ref ApiGatewayApi
  Outputs:
    ApiGatewayRegionalName:  
      Description: The arn of SNS Topic used to request a CNAME record. Share this with the subaccounts authorized to create resource records.
      Value: !Ref ApiGatewayApi
    #ApiGatewayRegionalHostedZoneId:
     #  Description: The Hosted zone id of the API
      # Value: !Ref ApiGatewayApi.RegionalHostedZoneId      
